POST http://localhost:8080/events/regEvent
Content-Type: application/json
Accept: */*


{
  "type": "Вечер живой музыки",
  "email": "bsgay2@mail.com",
  "name": "Генадий",
  "lastname": "Юсупов",
  "phone": "893016458719",
  "starts": "5-07-2019 21",
  "ends":"5-07-2019 22"
}

<> 2019-07-02T081731.200.json

###