POST http://localhost:8080/events/regEvent
Content-Type: application/json
Accept: */*


{
  "type": "День рождения",
  "email": "birthday2@mail.com",
  "name": "Евгений",
  "lastname": "Урбановский",
  "phone": "893044565319",
  "starts": "25-07-2019 14",
  "ends":"25-07-2019 18"
}

<> 2019-07-02T081731.200.json

###