POST http://localhost:8080/events/regEvent
Content-Type: application/json
Accept: */*


{
  "type": "Чаепитие",
  "email": "teafreak@mail.com",
  "name": "Эдуард",
  "lastname": "Кириллов",
  "phone": "89304687919",
  "starts": "08-07-2019 11",
  "ends":"08-07-2019 14"
}

<> 2019-07-02T081731.200.json

###