POST http://localhost:8080/events/regEvent
Content-Type: application/json
Accept: */*


{
  "type": "Rock Concert",
  "email": "34frae@mail.com",
  "name": "Антон",
  "lastname": "Антонов",
  "starts": "08-07 16",
  "ends":"08-07 18"
}

<> 2019-07-02T081731.200.json

###