POST http://localhost:8080/events/regEvent
Content-Type: application/json
Accept: */*


{
  "type": "Курсы от шефа2",
  "email": "34frae@mail.com",
  "name": "ООО ПОВАР2",
  "lastname": "",
  "phone": "89303239919",
  "starts": "16-07-2019 17",
  "ends":"16-07-2019 18"
}

<> 2019-07-02T081731.200.json

###