POST http://localhost:8080/events/regEvent
Content-Type: application/json
Accept: */*


{
  "email": "test@mail.com",
  "name": "Сергей",
  "lastname": "Сергеев",
  "starts": "04-07-2019 12:00:00",
  "ends":"04-07-2019 15:00:00"
}

<> 2019-07-02T081731.200.json

###